version: '3.9'
services:
  scc-cms:
    container_name: scc-cms
    restart: always
    build: ./scc-cms
    ports:
      - "8000:80"
    networks:
      - "scc"
  scc-api:
    container_name: scc-api
    restart: always
    build: ./scc-api
    ports:
      - "5000:80"
    environment:
      ASPNETCORE_ENVIRONMENT : Production
    networks:
      - "scc"

  mongo:
    container_name: scc-mongo
    image: mongo
    restart: always
    volumes:
      - ./scc-db/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    networks:
      - "scc"
  
volumes:
  mongo-data:

networks:
  scc:
