version: '3.9'
services:
  scc-cms:
    container_name: scc-cms
    restart: always
    build: ./scc-cms
    ports:
      - "8000:8000"
    networks:
      - "webnet"

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    networks:
      - "webnet"

networks:
  webnet:
